[project]
name = "downloads"
version = "1.1.0"
description = "Easy file downloads"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
